name: sds210-final-project
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex
  - _python_abi3_support
  - affine
  - anyio
  - appnope
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow
  - asttokens
  - async-lru
  - attrs
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - azure-core-cpp
  - azure-identity-cpp
  - azure-storage-blobs-cpp
  - azure-storage-common-cpp
  - azure-storage-files-datalake-cpp
  - babel
  - backports.zstd
  - beautifulsoup4
  - bleach
  - bleach-with-css
  - blosc
  - branca
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - cached-property
  - cached_property
  - certifi
  - cffi
  - charset-normalizer
  - click
  - click-plugins
  - cligj
  - comm
  - contextily
  - contourpy
  - cpython
  - cycler
  - debugpy
  - decorator
  - defusedxml
  - et_xmlfile
  - exceptiongroup
  - executing
  - folium
  - fonttools
  - fqdn
  - freetype
  - freexl
  - geographiclib
  - geopandas
  - geopandas-base
  - geopy
  - geos
  - gflags
  - giflib
  - glog
  - h11
  - h2
  - hpack
  - httpcore
  - httpx
  - hyperframe
  - icu
  - idna
  - importlib-metadata
  - ipykernel
  - ipython
  - ipython_pygments_lexers
  - isoduration
  - jedi
  - jinja2
  - joblib
  - json-c
  - json5
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - jsonschema-with-format-nongpl
  - jupyter-lsp
  - jupyter_client
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - kiwisolver
  - krb5
  - lark
  - lcms2
  - lerc
  - libabseil
  - libarchive
  - libarrow
  - libarrow-acero
  - libarrow-compute
  - libarrow-dataset
  - libarrow-substrait
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcrc32c
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libevent
  - libexpat
  - libffi
  - libfreetype
  - libfreetype6
  - libgcc
  - libgdal-core
  - libgfortran
  - libgfortran5
  - libgoogle-cloud
  - libgoogle-cloud-storage
  - libgrpc
  - libhwy
  - libiconv
  - libjpeg-turbo
  - libjxl
  - libkml
  - liblapack
  - liblzma
  - libnghttp2
  - libopenblas
  - libopentelemetry-cpp
  - libopentelemetry-cpp-headers
  - libparquet
  - libpng
  - libprotobuf
  - libre2-11
  - librttopo
  - libsodium
  - libspatialite
  - libsqlite
  - libssh2
  - libthrift
  - libtiff
  - libutf8proc
  - libwebp-base
  - libxcb
  - libxml2
  - libxml2-16
  - libxml2-devel
  - libzlib
  - llvm-openmp
  - lz4-c
  - lzo
  - mapclassify
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mercantile
  - minizip
  - mistune
  - munkres
  - muparser
  - nbclient
  - nbconvert-core
  - nbformat
  - ncurses
  - nest-asyncio
  - networkx
  - nlohmann_json
  - notebook-shim
  - numpy
  - openjpeg
  - openpyxl
  - openssl
  - orc
  - overrides
  - packaging
  - pandas
  - pandocfilters
  - parso
  - patsy
  - pcre2
  - pexpect
  - pillow
  - pip
  - platformdirs
  - proj
  - prometheus-cpp
  - prometheus_client
  - prompt-toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pyarrow
  - pyarrow-core
  - pycparser
  - pygments
  - pyobjc-core
  - pyobjc-framework-cocoa
  - pyogrio
  - pyparsing
  - pyproj
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-gil
  - python-json-logger
  - python-tzdata
  - python_abi
  - pyyaml
  - pyzmq
  - qhull
  - rasterio
  - re2
  - readline
  - referencing
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rfc3987-syntax
  - rioxarray
  - rpds-py
  - scikit-learn
  - scipy
  - seaborn
  - seaborn-base
  - send2trash
  - setuptools
  - shapely
  - six
  - snappy
  - sniffio
  - snuggs
  - soupsieve
  - sqlite
  - stack_data
  - statsmodels
  - terminado
  - threadpoolctl
  - tinycss2
  - tk
  - tomli
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - typing_extensions
  - typing_utils
  - tzdata
  - unicodedata2
  - uri-template
  - uriparser
  - urllib3
  - wcwidth
  - webcolors
  - webencodings
  - websocket-client
  - wheel
  - xarray
  - xerces-c
  - xorg-libxau
  - xorg-libxdmcp
  - xyzservices
  - yaml
  - zeromq
  - zipp
  - zlib
  - zlib-ng
  - zstd
